name: test-quilt-adrian

type: rails

up:
  - homebrew:
    - openssl
    - shopify/shopify/mysql-client:
        or:        [mysql]
        conflicts: [mysql-connector-c]
    # - another_package
  - ruby: 2.6.3
  - node:
      version: v10.11.0
      yarn: 1.12.3
  - bundler
  - railgun
  - database:
      bootstrap: bin/rails db:create db:migrate db:schema:load
      migrate: bin/rails db:migrate db:test:prepare
      host: test-quilt-adrian.railgun
      user: root
      password: ''
      database: test_quilt_adrian_development

server:
  port: 34092

commands:
  console: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    run:    bin/rails test

# These use fuzzy-matching, so you can (e.g.) `dev open app`
open:
  "My Application": https://test-quilt-adrian.myshopify.io
  #ops:
    # - https://datadog.link
    # - https://bugsnag.link
    # - https://kafka.link
